/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StaffRole;

import userinterface.Incident.IncidentReportingJPanel;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.StaffOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.Incident.ManageIncidentsJPanel;


/**
 *
 * @author Sweta Chowdhury
 */
public class StaffWorkAreaPanel extends javax.swing.JPanel {

    
    private JPanel userProcessContainer;
    private StaffOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
    /**
     * Creates new form StaffWorkAreaPanel
     */
    public StaffWorkAreaPanel(JPanel userProcessContainer, UserAccount account, StaffOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        requestButton = new javax.swing.JButton();
        reportIncident = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("WELCOME TO STAFF WORK AREA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, 41));

        requestButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        requestButton.setText(" REQUEST MANAGEMENT");
        requestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestButtonActionPerformed(evt);
            }
        });
        add(requestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 330, 70));

        reportIncident.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        reportIncident.setText("REPORT INCIDENT");
        reportIncident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportIncidentActionPerformed(evt);
            }
        });
        add(reportIncident, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 330, 70));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("VIEW MANDATORY TRAINIGNS");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 330, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void reportIncidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportIncidentActionPerformed
        // TODO add your handling code here:
//        IncidentReportingJPanel reportIncidentJPanel = new IncidentReportingJPanel(userProcessContainer, userAccount, enterprise);
//        userProcessContainer.add("reportIncidentJPanel", reportIncidentJPanel);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.next(userProcessContainer);
        
        ManageIncidentsJPanel manageIncidentJPanel = new ManageIncidentsJPanel(userProcessContainer, enterprise, userAccount, business);
        userProcessContainer.add("manageIncidentJPanel", manageIncidentJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_reportIncidentActionPerformed

    private void requestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestButtonActionPerformed
        // TODO add your handling code here:
        ManageRequestsJPanel manageRequestsJPanel = new ManageRequestsJPanel(userProcessContainer, userAccount, enterprise);
        userProcessContainer.add("manageRequestsJPanel", manageRequestsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_requestButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton reportIncident;
    private javax.swing.JButton requestButton;
    // End of variables declaration//GEN-END:variables
}
