/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HousingAdmin;

import Business.Housing.Housing;
import Business.Organization.Organization;
import Business.Housing.Housing.shelterType;
import Business.Housing.Housing.statusType;
import Business.Organization.HousingOrganization;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sweta Chowdhury
 */
public class ManageShelterJPanel extends javax.swing.JPanel {

    
    private JPanel userProcessContainer;
    private HousingOrganization organization;
    
    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageShelterJPanel(JPanel userProcessContainer, HousingOrganization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        
        populateCombo();
    }

    
    public void populateCombo() {
        shelterTypeJComboBox.removeAllItems();
        
        for(shelterType type: Housing.shelterType.values()){
            shelterTypeJComboBox.addItem(type);
        }

        addressJComboBox.removeAllItems();
        
//        for(Network network: this.business.getNetworkList()){
            //network.
            addressJComboBox.addItem("Boston");
//        }
        
        shelterStatusJComboBox.removeAllItems();
        
        for(statusType type: Housing.statusType.values()){
            shelterStatusJComboBox.addItem(type);
        }
        
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sName = new javax.swing.JLabel();
        shelterStatusJComboBox = new javax.swing.JComboBox();
        addJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        shelterCapacity = new javax.swing.JTextField();
        shelterTypeJComboBox = new javax.swing.JComboBox();
        addressJComboBox = new javax.swing.JComboBox();
        shelterName = new javax.swing.JTextField();
        shelterPhone = new javax.swing.JTextField();
        shelterEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        shelterContactPerson = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("MANAGE HOUSING WORKAREA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, 41));

        sName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sName.setText("Shelter Name:");
        add(sName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 210, 30));

        shelterStatusJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        shelterStatusJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shelterStatusJComboBoxActionPerformed(evt);
            }
        });
        add(shelterStatusJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 190, 30));

        addJButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        addJButton.setText("ADD HOUSING");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });
        add(addJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 250, 40));

        backJButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        backJButton.setText("<<BACK");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 170, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Email:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 210, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Address:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 210, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Contact Person:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 210, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Type of Shelter:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 210, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Phone:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 210, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Shelter capacity:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 210, 30));

        shelterCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shelterCapacityActionPerformed(evt);
            }
        });
        add(shelterCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 190, 30));

        shelterTypeJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        shelterTypeJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shelterTypeJComboBoxActionPerformed(evt);
            }
        });
        add(shelterTypeJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 190, 30));

        addressJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        addressJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressJComboBoxActionPerformed(evt);
            }
        });
        add(addressJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 190, 30));

        shelterName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shelterNameActionPerformed(evt);
            }
        });
        add(shelterName, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 190, 30));

        shelterPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shelterPhoneActionPerformed(evt);
            }
        });
        add(shelterPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 190, 30));

        shelterEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shelterEmailActionPerformed(evt);
            }
        });
        add(shelterEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 190, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Status:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 210, 30));

        shelterContactPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shelterContactPersonActionPerformed(evt);
            }
        });
        add(shelterContactPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 190, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

        Component[] components = userProcessContainer.getComponents();
        for(Component c: components){
           if(c instanceof ManageOrganizationJPanel){
               ManageOrganizationJPanel manageOrganizationJPanel = (ManageOrganizationJPanel)c;
               manageOrganizationJPanel.populateTable();
           }
        }        
    }//GEN-LAST:event_backJButtonActionPerformed

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
//housing.se
        if (shelterName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Some fields are blank.Please enter values");
            return;
        } 
        else {
        Housing housing = this.organization.getHousingDirectory().createAndAddHousing();

        housing.setHouseName(shelterName.getText());
        housing.setHouseType(shelterTypeJComboBox.getSelectedItem().toString());
        housing.setHousePhone(shelterPhone.getText());
        housing.setHouseEmail(shelterEmail.getText());
        housing.setHouseAddress(addressJComboBox.getSelectedItem().toString());
        housing.setHouseCapacity(shelterCapacity.getText());
        housing.setHouseStatus(shelterStatusJComboBox.getSelectedItem().toString());

            JOptionPane.showMessageDialog(null, "Shelter added successfully", "Warning", JOptionPane.INFORMATION_MESSAGE);
            shelterName.setText(null);
            shelterTypeJComboBox.setSelectedItem(null);
            shelterPhone.setText(null);
            shelterEmail.setText(null);
            addressJComboBox.setSelectedItem(null);
            shelterCapacity.setText(null);
            shelterContactPerson.setText(null);
            shelterStatusJComboBox.setSelectedItem(null);
        }
        //txtAirlinerName.setText("");
        
        /*OrganizationType type = (OrganizationType) shelterStatusJComboBox.getSelectedItem();
        directory.createOrganization(type);
        populateTable();*/
    }//GEN-LAST:event_addJButtonActionPerformed

    private void shelterStatusJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shelterStatusJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shelterStatusJComboBoxActionPerformed

    private void shelterTypeJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shelterTypeJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shelterTypeJComboBoxActionPerformed

    private void shelterCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shelterCapacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shelterCapacityActionPerformed

    private void addressJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressJComboBoxActionPerformed

    private void shelterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shelterNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shelterNameActionPerformed

    private void shelterPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shelterPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shelterPhoneActionPerformed

    private void shelterEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shelterEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shelterEmailActionPerformed

    private void shelterContactPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shelterContactPersonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shelterContactPersonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JComboBox addressJComboBox;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel sName;
    private javax.swing.JTextField shelterCapacity;
    private javax.swing.JTextField shelterContactPerson;
    private javax.swing.JTextField shelterEmail;
    private javax.swing.JTextField shelterName;
    private javax.swing.JTextField shelterPhone;
    private javax.swing.JComboBox shelterStatusJComboBox;
    private javax.swing.JComboBox shelterTypeJComboBox;
    // End of variables declaration//GEN-END:variables
}
