/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ReliefOrgAdmin;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Incident.Incident;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sweta Chowdhury
 */
public class ViewIncidentsJPanel extends javax.swing.JPanel {
    private JPanel container;
    private Enterprise enterprise;
    private UserAccount account;
    private EcoSystem system;
    /**
     * Creates new form ViewIncidentsJPanel
     */
    public ViewIncidentsJPanel(JPanel container, Enterprise enterprise, UserAccount account, EcoSystem system) {
        initComponents();
        this.enterprise = enterprise;
        this.container = container;
        this.account = account;
        this.system = system;
        populateTable();
    }
    
    public void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) incidentsJTable.getModel();
        model.setRowCount(0);

        for(Incident incident: enterprise.getIncidentDirectory().getIncidentList()) {
            Object[] row = new Object[model.getColumnCount()];
                row[0] = incident;
                row[1] = incident.getEventType();
                row[2] = incident.getIncidentType();
                row[3] = incident.getDateOccured();
                row[4] = incident.getCity();
               
                model.addRow(row);
        }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        incidentsJTable = new javax.swing.JTable();
        backButton = new javax.swing.JButton();
        requestResourcesButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("VIEW REPORTED INCIDENTS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, 41));

        incidentsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Incident Name", "Event Type", "Incident Type", "Date of Occurrence", "Location"
            }
        ));
        jScrollPane1.setViewportView(incidentsJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 960, 210));

        backButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        backButton.setText("<<BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 190, 60));

        requestResourcesButton.setText("Manage Requests");
        requestResourcesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestResourcesButtonActionPerformed(evt);
            }
        });
        add(requestResourcesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 380, 210, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backButtonActionPerformed

    private void requestResourcesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestResourcesButtonActionPerformed
        // TODO add your handling code here:
        if (incidentsJTable.getSelectedRow() >= 0) {
            ManageRequests manageRequests = new ManageRequests(container, (Incident)incidentsJTable.getValueAt(incidentsJTable.getSelectedRow(),0), account, enterprise, system);
            CardLayout layout = (CardLayout) container.getLayout();
            container.add("ManageRequests",manageRequests);
            layout.next(container);
        }
        else {
            JOptionPane.showMessageDialog(this, "Please select an incident");
        }
    }//GEN-LAST:event_requestResourcesButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTable incidentsJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton requestResourcesButton;
    // End of variables declaration//GEN-END:variables
}
