/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DisasterVictimRegistry;

import Business.DisasterRegistry.DisasterVictim;
import Business.Organization.DisasterVictimOrganization;
import java.awt.CardLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import static userinterface.DisasterVictimRegistry.CreateVictimJPanel.scaleImage;

/**
 *
 * @author mamta
 */
public class ViewVictimJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewVictimJPanel
     */
    JPanel userProcessContainer;
    DisasterVictimOrganization organization;
    //WorkRequest workrequest;
    public ViewVictimJPanel(JPanel userProcessContainer, DisasterVictimOrganization organization) {
        initComponents();
        this.organization = organization;
        this.userProcessContainer = userProcessContainer;
        
        populateVictimCombo();
    }

    public void populateVictimCombo() {
        victimCombo.removeAllItems();
        victimCombo.addItem("Victim");
        victimCombo.addItem("Missing Person");
        
    }
    
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) victimTbl.getModel();
        model.setRowCount(0);
                
        if(victimCombo.getItemCount()>0){
            if(victimCombo.getSelectedItem().equals("Victim")){
            for(DisasterVictim dv : organization.getDisasterVictimDirectory().getVictimList()) {
                if(dv.getType().equals("Victim")){
                    Object[] row = new Object[model.getColumnCount()];
                    row[0] = dv;
                    row[1] = dv.getAge();
                    row[2] = dv.getGender();
                    row[3] = dv.getAddress();
                    row[4] = dv.getContact();
                    row[5] = dv.getNationality();
                    row[6] = dv.getType();
                    model.addRow(row);
                }
        }
            }else if(victimCombo.getSelectedItem().equals("Missing Person")){
            for(DisasterVictim dv : organization.getDisasterVictimDirectory().getVictimList()) {
                if(dv.getType().equals("Missing Person")){
                    Object[] row = new Object[model.getColumnCount()];
                    row[0] = dv;
                    row[1] = dv.getAge();
                    row[2] = dv.getGender();
                    row[3] = dv.getAddress();
                    row[4] = dv.getContact();
                    row[5] = dv.getNationality();
                    row[6] = dv.getType();
                    model.addRow(row);
                } 
        } 
        } 
        }          
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        victimTbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        imgBtn = new javax.swing.JButton();
        imgLbl = new javax.swing.JLabel();
        victimCombo = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();

        victimTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Age", "Gender", "Address", "Contact", "Nationality", "Type"
            }
        ));
        jScrollPane1.setViewportView(victimTbl);

        jButton1.setText("< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        imgBtn.setText("View Image");
        imgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imgBtnActionPerformed(evt);
            }
        });

        victimCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        victimCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                victimComboItemStateChanged(evt);
            }
        });
        victimCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                victimComboActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setText("VICTIMS REGISTRY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(victimCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(imgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addComponent(imgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(victimCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(imgBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(imgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void imgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imgBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = victimTbl.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select the row to delete the account", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            DisasterVictim dv = (DisasterVictim) victimTbl.getValueAt(selectedRow, 0);
            Icon img = dv.getImage();
            imgLbl.setIcon(img);
        
        try {
             File file = dv.getFile();
             BufferedImage image = ImageIO.read(new File(file.getAbsolutePath()));
             ImageIcon image1=new ImageIcon(scaleImage(314, 288, image));//get the image from file chooser and scale it to match JLabel size
             imgLbl.setIcon(image1);
            } catch (Exception ex) {}              
        }
    }//GEN-LAST:event_imgBtnActionPerformed

    private void victimComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_victimComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_victimComboActionPerformed

    private void victimComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_victimComboItemStateChanged
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_victimComboItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton imgBtn;
    private javax.swing.JLabel imgLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox victimCombo;
    private javax.swing.JTable victimTbl;
    // End of variables declaration//GEN-END:variables
}
