/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.VolunteerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.StaffOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.Incident.ManageIncidentsJPanel;
import userinterface.StaffAndVolunteerAdmin.AddNewStaffJPanel;

/**
 *
 * @author Sweta Chowdhury
 */
public class VolunteerWorkAreaPanel extends javax.swing.JPanel {

    
    private JPanel userProcessContainer;
    private StaffOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
    /**
     * Creates new form VolunteerWorkAreaPanel
     */
    public VolunteerWorkAreaPanel(JPanel userProcessContainer, UserAccount account, StaffOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        donationButton = new javax.swing.JButton();
        reportIncidentButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("WELCOME TO VOLUNTEER WORK AREA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, 41));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("VIEW TRAININGS");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 310, 60));

        donationButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        donationButton.setText("MAKE DONATION");
        donationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donationButtonActionPerformed(evt);
            }
        });
        add(donationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 310, 60));

        reportIncidentButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        reportIncidentButton.setText("REPORT INCIDENT");
        reportIncidentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportIncidentButtonActionPerformed(evt);
            }
        });
        add(reportIncidentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 310, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void reportIncidentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportIncidentButtonActionPerformed
        // TODO add your handling code here:
        ManageIncidentsJPanel manageIncidentJPanel = new ManageIncidentsJPanel(userProcessContainer, enterprise, userAccount, business);
        userProcessContainer.add("manageIncidentJPanel", manageIncidentJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_reportIncidentButtonActionPerformed

    private void donationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donationButtonActionPerformed
        // TODO add your handling code here:
//        MakeADonationJPanel donationJPanel = new MakeADonationJPanel(userProcessContainer, userAccount, organization, enterprise, business);
//        userProcessContainer.add("donationJPanel", donationJPanel);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.next(userProcessContainer);
        
        NonEmergencyJPanel donationJPanel = new NonEmergencyJPanel(userProcessContainer, organization, userAccount, enterprise, business);
        userProcessContainer.add("donationJPanel", donationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_donationButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton donationButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton reportIncidentButton;
    // End of variables declaration//GEN-END:variables
}
