/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StaffAndVolunteerAdmin;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.StaffOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Sweta Chowdhury
 */
public class StaffAndVolunteerAdminWorkAreaJPanel extends javax.swing.JPanel {

    
    private JPanel userProcessContainer;
    private UserAccount account;
    private StaffOrganization organization;
    private Enterprise enterprise;
    private EcoSystem business;
    
    /**
     * Creates new form StaffAndVolunteerAdminWorkAreaJPanel
     */
    public StaffAndVolunteerAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, StaffOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account; 
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageOrganizationJButton = new javax.swing.JButton();
        trainingsButton = new javax.swing.JButton();
        requestsButton = new javax.swing.JButton();
        userAccountsButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("WELCOME TO STAFF AND VOLUNTEER ADMIN WORK AREA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, 41));

        manageOrganizationJButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        manageOrganizationJButton.setText("MANAGE STAFF AND VOLUNTEERS");
        manageOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationJButtonActionPerformed(evt);
            }
        });
        add(manageOrganizationJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 360, 60));

        trainingsButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        trainingsButton.setText("MANAGE TRAININGS");
        trainingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainingsButtonActionPerformed(evt);
            }
        });
        add(trainingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 360, 60));

        requestsButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        requestsButton.setText("MANAGE REQUESTS");
        requestsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestsButtonActionPerformed(evt);
            }
        });
        add(requestsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 360, 60));

        userAccountsButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        userAccountsButton.setText("MANAGE USER ACCOUNTS");
        userAccountsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userAccountsButtonActionPerformed(evt);
            }
        });
        add(userAccountsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 360, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void manageOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonActionPerformed
        ManageStaffJPanel manageStaffJPanel = new ManageStaffJPanel(userProcessContainer, account, organization, enterprise, business);
        userProcessContainer.add("manageStaffJPanel", manageStaffJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganizationJButtonActionPerformed

    private void userAccountsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userAccountsButtonActionPerformed
        // TODO add your handling code here:
        ManageUsersJPanel manageUsersJPanel = new ManageUsersJPanel(userProcessContainer, account, organization, enterprise, business);
        userProcessContainer.add("manageUsersJPanel", manageUsersJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_userAccountsButtonActionPerformed

    private void trainingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainingsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trainingsButtonActionPerformed

    private void requestsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestsButtonActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_requestsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageOrganizationJButton;
    private javax.swing.JButton requestsButton;
    private javax.swing.JButton trainingsButton;
    private javax.swing.JButton userAccountsButton;
    // End of variables declaration//GEN-END:variables
}
